from app.database import SessionLocal, engine
from app.models.challenge import Challenge, Difficulty, GameMode, Language
from app.database import Base

CHALLENGES = [
    {"title":"Hello, World!","description":"Write a function that returns the string 'Hello, World!'.","story":"Your first spell in the arena.","difficulty":Difficulty.easy,"game_mode":GameMode.puzzle,"language":Language.python,"level_req":1,"starter_code":"def greet():\n    pass","solution":"def greet():\n    return 'Hello, World!'","test_cases":[{"input":[],"expected_output":"Hello, World!"}],"hints":["Use the return keyword","Return a string with quotes"],"xp_reward":100,"time_limit":120},
    {"title":"Sum of Two Numbers","description":"Write a function that returns the sum of two numbers a and b.","story":None,"difficulty":Difficulty.easy,"game_mode":GameMode.puzzle,"language":Language.python,"level_req":1,"starter_code":"def add(a, b):\n    pass","solution":"def add(a, b):\n    return a + b","test_cases":[{"input":[2,3],"expected_output":"5"},{"input":[-1,1],"expected_output":"0"},{"input":[100,200],"expected_output":"300"}],"hints":["Use the + operator","return a + b"],"xp_reward":100,"time_limit":120},
    {"title":"Is Even","description":"Return True if a number is even, False otherwise.","story":None,"difficulty":Difficulty.easy,"game_mode":GameMode.puzzle,"language":Language.python,"level_req":1,"starter_code":"def is_even(n):\n    pass","solution":"def is_even(n):\n    return n % 2 == 0","test_cases":[{"input":[4],"expected_output":"True"},{"input":[7],"expected_output":"False"},{"input":[0],"expected_output":"True"}],"hints":["Use % operator","n % 2 == 0 means even"],"xp_reward":100,"time_limit":120},
    {"title":"Maximum of Three","description":"Return the largest of three numbers without using max().","story":None,"difficulty":Difficulty.easy,"game_mode":GameMode.puzzle,"language":Language.python,"level_req":1,"starter_code":"def max_three(a, b, c):\n    pass","solution":"def max_three(a, b, c):\n    if a >= b and a >= c: return a\n    elif b >= c: return b\n    return c","test_cases":[{"input":[1,2,3],"expected_output":"3"},{"input":[10,5,8],"expected_output":"10"},{"input":[-1,-5,-3],"expected_output":"-1"}],"hints":["Use if/elif/else","Compare each number"],"xp_reward":100,"time_limit":150},
    {"title":"FizzBuzz","description":"Return a list for numbers 1 to n. Multiples of 3: 'Fizz', 5: 'Buzz', both: 'FizzBuzz', else number as string.","story":"The dungeon gate is locked by a riddle. Solve FizzBuzz to proceed.","difficulty":Difficulty.medium,"game_mode":GameMode.quest,"language":Language.python,"level_req":1,"starter_code":"def fizzbuzz(n):\n    result = []\n    return result","solution":"def fizzbuzz(n):\n    result = []\n    for i in range(1, n+1):\n        if i%15==0: result.append('FizzBuzz')\n        elif i%3==0: result.append('Fizz')\n        elif i%5==0: result.append('Buzz')\n        else: result.append(str(i))\n    return result","test_cases":[{"input":[5],"expected_output":"['1', '2', 'Fizz', '4', 'Buzz']"},{"input":[15],"expected_output":"['1', '2', 'Fizz', '4', 'Buzz', 'Fizz', '7', '8', 'Fizz', 'Buzz', '11', 'Fizz', '13', '14', 'FizzBuzz']"}],"hints":["Check 15 first","Use range(1, n+1)","Convert numbers to str()"],"xp_reward":250,"time_limit":300},
    {"title":"Reverse a String","description":"Return the reverse of a string without using slicing [::-1].","story":None,"difficulty":Difficulty.medium,"game_mode":GameMode.battle,"language":Language.python,"level_req":1,"starter_code":"def reverse_string(s):\n    pass","solution":"def reverse_string(s):\n    result = ''\n    for ch in s:\n        result = ch + result\n    return result","test_cases":[{"input":["hello"],"expected_output":"olleh"},{"input":["Python"],"expected_output":"nohtyP"},{"input":[""],"expected_output":""}],"hints":["Loop through each character","Prepend each character"],"xp_reward":250,"time_limit":300},
    {"title":"Palindrome Check","description":"Return True if a string is a palindrome (ignore case and spaces).","story":"The temple door has a riddle about words that read the same forwards and backwards.","difficulty":Difficulty.medium,"game_mode":GameMode.debug,"language":Language.python,"level_req":1,"starter_code":"def is_palindrome(s):\n    s = s.lower().replace(' ', '')\n    pass","solution":"def is_palindrome(s):\n    s = s.lower().replace(' ', '')\n    return s == s[::-1]","test_cases":[{"input":["racecar"],"expected_output":"True"},{"input":["hello"],"expected_output":"False"},{"input":["A man a plan a canal Panama"],"expected_output":"True"}],"hints":["Convert to lowercase","Remove spaces","Compare string to its reverse"],"xp_reward":250,"time_limit":300},
    {"title":"Count Vowels","description":"Return the number of vowels (a,e,i,o,u) in a string (case insensitive).","story":None,"difficulty":Difficulty.medium,"game_mode":GameMode.puzzle,"language":Language.python,"level_req":1,"starter_code":"def count_vowels(s):\n    pass","solution":"def count_vowels(s):\n    return sum(1 for c in s.lower() if c in 'aeiou')","test_cases":[{"input":["Hello World"],"expected_output":"3"},{"input":["Python"],"expected_output":"1"},{"input":["aeiou"],"expected_output":"5"}],"hints":["Loop through characters","Check if in 'aeiou'","Use .lower()"],"xp_reward":250,"time_limit":300},
    {"title":"Find Duplicates","description":"Return a sorted list of all duplicate elements in a list.","story":None,"difficulty":Difficulty.medium,"game_mode":GameMode.puzzle,"language":Language.python,"level_req":1,"starter_code":"def find_duplicates(arr):\n    pass","solution":"def find_duplicates(arr):\n    seen=set(); dupes=set()\n    for x in arr:\n        if x in seen: dupes.add(x)\n        seen.add(x)\n    return sorted(list(dupes))","test_cases":[{"input":[[1,2,3,2,4,3]],"expected_output":"[2, 3]"},{"input":[[1,2,3]],"expected_output":"[]"},{"input":[[5,5,5]],"expected_output":"[5]"}],"hints":["Use a set to track seen elements","Add to duplicates if already seen","Sort the final result"],"xp_reward":250,"time_limit":360},
    {"title":"Binary Search","description":"Implement binary search on a sorted list. Return index of target, or -1 if not found.","story":"A million scrolls in the dragon's lair. Search smart or lose.","difficulty":Difficulty.hard,"game_mode":GameMode.battle,"language":Language.python,"level_req":1,"starter_code":"def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    pass","solution":"def binary_search(arr, target):\n    left, right = 0, len(arr)-1\n    while left <= right:\n        mid = (left+right)//2\n        if arr[mid]==target: return mid\n        elif arr[mid]<target: left=mid+1\n        else: right=mid-1\n    return -1","test_cases":[{"input":[[1,3,5,7,9],5],"expected_output":"2"},{"input":[[1,3,5,7,9],6],"expected_output":"-1"},{"input":[[2,4,6,8,10],10],"expected_output":"4"}],"hints":["mid = (left+right)//2","If target > arr[mid], search right","If target < arr[mid], search left"],"xp_reward":500,"time_limit":600},
    {"title":"Two Sum","description":"Return sorted indices of two numbers that add up to target.","story":None,"difficulty":Difficulty.hard,"game_mode":GameMode.puzzle,"language":Language.python,"level_req":1,"starter_code":"def two_sum(nums, target):\n    pass","solution":"def two_sum(nums, target):\n    seen={}\n    for i,n in enumerate(nums):\n        comp=target-n\n        if comp in seen: return sorted([seen[comp],i])\n        seen[n]=i\n    return []","test_cases":[{"input":[[2,7,11,15],9],"expected_output":"[0, 1]"},{"input":[[3,2,4],6],"expected_output":"[1, 2]"},{"input":[[3,3],6],"expected_output":"[0, 1]"}],"hints":["Use a hash map","For each number look for complement","complement = target - current"],"xp_reward":500,"time_limit":600},
    {"title":"Flatten Nested List","description":"Flatten an arbitrarily nested list into a single flat list.","story":None,"difficulty":Difficulty.hard,"game_mode":GameMode.puzzle,"language":Language.python,"level_req":1,"starter_code":"def flatten(lst):\n    pass","solution":"def flatten(lst):\n    result=[]\n    for item in lst:\n        if isinstance(item,list): result.extend(flatten(item))\n        else: result.append(item)\n    return result","test_cases":[{"input":[[[1,[2,3]],[4,[5,[6]]]]],"expected_output":"[1, 2, 3, 4, 5, 6]"},{"input":[[[1,2],[3,4]]],"expected_output":"[1, 2, 3, 4]"},{"input":[[1,2,3]],"expected_output":"[1, 2, 3]"}],"hints":["Use recursion","Check isinstance(item, list)","Use extend()"],"xp_reward":500,"time_limit":600},
    {"title":"BOSS: Fibonacci Memoization","description":"Return nth Fibonacci number using memoization. Must handle n=30 efficiently.","story":"BOSS FIGHT! The Ancient Dragon Fibonacci blocks your path. Brute force will fail.","difficulty":Difficulty.boss,"game_mode":GameMode.boss,"language":Language.python,"level_req":1,"starter_code":"def fib(n, memo={}):\n    pass","solution":"def fib(n, memo={}):\n    if n in memo: return memo[n]\n    if n <= 1: return n\n    memo[n] = fib(n-1,memo) + fib(n-2,memo)\n    return memo[n]","test_cases":[{"input":[0],"expected_output":"0"},{"input":[1],"expected_output":"1"},{"input":[10],"expected_output":"55"},{"input":[30],"expected_output":"832040"}],"hints":["Base case: n<=1 return n","Check if n is in memo dict","Store result in memo before returning"],"xp_reward":1000,"time_limit":900},
    {"title":"BOSS: Valid Parentheses","description":"Return True if all brackets (), {}, [] are properly closed and nested.","story":"BOSS FIGHT! The Bracket Demon. Destroy every unmatched bracket.","difficulty":Difficulty.boss,"game_mode":GameMode.boss,"language":Language.python,"level_req":1,"starter_code":"def is_valid(s):\n    pass","solution":"def is_valid(s):\n    stack=[]; mapping={')':'(', '}':'{', ']':'['}\n    for char in s:\n        if char in '({[': stack.append(char)\n        elif char in mapping:\n            if not stack or stack[-1]!=mapping[char]: return False\n            stack.pop()\n    return len(stack)==0","test_cases":[{"input":["()[]{}"],"expected_output":"True"},{"input":["([)]"],"expected_output":"False"},{"input":["{[]}"],"expected_output":"True"},{"input":["("],"expected_output":"False"}],"hints":["Use a stack","Push opening brackets","For closing, check top of stack"],"xp_reward":1000,"time_limit":900},
    {"title":"BOSS: Merge Sort","description":"Implement merge sort. Return the sorted list with O(n log n) complexity.","story":"MEGA BOSS: The Sort Titan. Bubble sort will be destroyed. Only O(n log n) survives.","difficulty":Difficulty.boss,"game_mode":GameMode.boss,"language":Language.python,"level_req":1,"starter_code":"def merge_sort(arr):\n    pass","solution":"def merge_sort(arr):\n    if len(arr)<=1: return arr\n    mid=len(arr)//2\n    left=merge_sort(arr[:mid]); right=merge_sort(arr[mid:])\n    result=[]; i=j=0\n    while i<len(left) and j<len(right):\n        if left[i]<=right[j]: result.append(left[i]); i+=1\n        else: result.append(right[j]); j+=1\n    result.extend(left[i:]); result.extend(right[j:])\n    return result","test_cases":[{"input":[[5,2,8,1,9,3]],"expected_output":"[1, 2, 3, 5, 8, 9]"},{"input":[[1]],"expected_output":"[1]"},{"input":[[-3,0,5,-1,2]],"expected_output":"[-3, -1, 0, 2, 5]"}],"hints":["Split array in half recursively","Merge two sorted halves","Compare elements one by one"],"xp_reward":1500,"time_limit":1200},
    {"title":"Arrow Function","description":"Write a function that doubles a number.","story":None,"difficulty":Difficulty.easy,"game_mode":GameMode.puzzle,"language":Language.javascript,"level_req":1,"starter_code":"function double(n) {\n  return null;\n}","solution":"function double(n) {\n  return n * 2;\n}","test_cases":[{"input":[5],"expected_output":"10"},{"input":[0],"expected_output":"0"},{"input":[-3],"expected_output":"-6"}],"hints":["Multiply by 2","return n * 2"],"xp_reward":100,"time_limit":120},
    {"title":"Array Sum","description":"Return the sum of all numbers in an array.","story":None,"difficulty":Difficulty.easy,"game_mode":GameMode.puzzle,"language":Language.javascript,"level_req":1,"starter_code":"function arraySum(arr) {\n  return 0;\n}","solution":"function arraySum(arr) {\n  return arr.reduce((acc, val) => acc + val, 0);\n}","test_cases":[{"input":[[1,2,3,4,5]],"expected_output":"15"},{"input":[[]],"expected_output":"0"},{"input":[[-1,1]],"expected_output":"0"}],"hints":["Use arr.reduce()","Start with 0 as initial value"],"xp_reward":100,"time_limit":120},
    {"title":"Filter Evens","description":"Return only the even numbers from an array.","story":None,"difficulty":Difficulty.easy,"game_mode":GameMode.puzzle,"language":Language.javascript,"level_req":1,"starter_code":"function filterEvens(arr) {\n  return [];\n}","solution":"function filterEvens(arr) {\n  return arr.filter(n => n % 2 === 0);\n}","test_cases":[{"input":[[1,2,3,4,5,6]],"expected_output":"[2,4,6]"},{"input":[[1,3,5]],"expected_output":"[]"}],"hints":["Use arr.filter()","n % 2 === 0 checks even"],"xp_reward":100,"time_limit":120},
    {"title":"C++: Fibonacci","description":"Return the nth Fibonacci number using iteration (no recursion).","story":None,"difficulty":Difficulty.easy,"game_mode":GameMode.puzzle,"language":Language.cpp,"level_req":1,"starter_code":"int fibonacci(int n) {\n    return 0;\n}","solution":"int fibonacci(int n) {\n    if(n<=1) return n;\n    int a=0,b=1;\n    for(int i=2;i<=n;i++){int c=a+b;a=b;b=c;}\n    return b;\n}","test_cases":[{"input":[0],"expected_output":"0"},{"input":[1],"expected_output":"1"},{"input":[10],"expected_output":"55"}],"hints":["Use two variables a and b","Loop from 2 to n","Update: temp=a+b, a=b, b=temp"],"xp_reward":100,"time_limit":180},
    {"title":"C++: Count Characters","description":"Count how many times a character appears in a string.","story":None,"difficulty":Difficulty.easy,"game_mode":GameMode.puzzle,"language":Language.cpp,"level_req":1,"starter_code":"int countChar(std::string s, char c) {\n    return 0;\n}","solution":"int countChar(std::string s, char c) {\n    int count=0;\n    for(char ch:s) if(ch==c) count++;\n    return count;\n}","test_cases":[{"input":["hello","l"],"expected_output":"2"},{"input":["mississippi","s"],"expected_output":"4"}],"hints":["Use range-based for loop","Compare each char to c","Increment counter"],"xp_reward":100,"time_limit":180},
    {"title":"Java: String Reverse","description":"Return the reverse of a string using StringBuilder.","story":"Welcome to Java arena.","difficulty":Difficulty.easy,"game_mode":GameMode.puzzle,"language":Language.java,"level_req":1,"starter_code":"public static String reverseString(String s) {\n    return \"\";\n}","solution":"public static String reverseString(String s) {\n    return new StringBuilder(s).reverse().toString();\n}","test_cases":[{"input":["hello"],"expected_output":"olleh"},{"input":["Java"],"expected_output":"avaJ"}],"hints":["Create new StringBuilder(s)",".reverse() then .toString()"],"xp_reward":100,"time_limit":150},
    {"title":"Java: Armstrong Number","description":"Return true if n is an Armstrong number (sum of digits each raised to power of digit count equals n).","story":None,"difficulty":Difficulty.easy,"game_mode":GameMode.puzzle,"language":Language.java,"level_req":1,"starter_code":"public static boolean isArmstrong(int n) {\n    return false;\n}","solution":"public static boolean isArmstrong(int n) {\n    String s=Integer.toString(n); int power=s.length(),sum=0;\n    for(char c:s.toCharArray()) sum+=Math.pow(Character.getNumericValue(c),power);\n    return sum==n;\n}","test_cases":[{"input":[153],"expected_output":"true"},{"input":[370],"expected_output":"true"},{"input":[123],"expected_output":"false"}],"hints":["Convert to string to get digits","Power = number of digits","Sum each digit raised to power"],"xp_reward":100,"time_limit":180},
]

def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        existing = db.query(Challenge).count()
        if existing > 0:
            print(f"Already {existing} challenges exist. Skipping seed.")
            return
        for data in CHALLENGES:
            db.add(Challenge(**data))
        db.commit()
        print(f"Seeded {len(CHALLENGES)} challenges successfully!")
    finally:
        db.close()

if __name__ == "__main__":
    seed()
